#!/bin/bash

echo "AWS OIDC Setup Checklist for Frontend CI/CD"
echo "==========================================="
echo ""
echo "✓ Required GitHub Secret:"
echo "  [ ] AWS_ACCOUNT_ID is set in repository secrets"
echo ""
echo "✓ IAM Role Setup:"
echo "  [ ] Role 'terraform-deployer-ai-lifestyle' exists in your AWS account"
echo "  [ ] Role has proper permissions for:"
echo "      - S3 bucket operations"
echo "      - CloudFront operations"
echo "      - Terraform state access"
echo "  [ ] Role has trust policy allowing GitHub Actions OIDC"
echo ""
echo "✓ GitHub OIDC Provider:"
echo "  [ ] OIDC provider 'token.actions.githubusercontent.com' exists in AWS IAM"
echo "  [ ] Provider thumbprint is configured"
echo ""
echo "✓ Optional Cleanup:"
echo "  [ ] Remove AWS_ACCESS_KEY_ID from secrets"
echo "  [ ] Remove AWS_SECRET_ACCESS_KEY from secrets"
echo "  [ ] Remove AWS_ACCESS_KEY_ID_PROD from secrets"
echo "  [ ] Remove AWS_SECRET_ACCESS_KEY_PROD from secrets"
echo ""
echo "✓ Test the Setup:"
echo "  1. Push changes to a branch"
echo "  2. Create a pull request"
echo "  3. Check if 'Configure AWS credentials' step succeeds"
echo ""
echo "For detailed setup instructions, see AWS_AUTH_UPDATE.md"
