#!/bin/bash

echo "GitHub Secrets Checklist for Frontend CI/CD"
echo "==========================================="
echo ""
echo "Go to: Settings → Secrets and variables → Actions"
echo ""
echo "Required Secrets:"
echo ""
echo "[ ] AWS_ACCOUNT_ID"
echo "    Your 12-digit AWS account ID"
echo "    Example: 123456789012"
echo ""
echo "Development Environment:"
echo "[ ] DEV_API_URL"
echo "    Example: https://abc123.execute-api.us-east-1.amazonaws.com/v1"
echo ""
echo "[ ] DEV_COGNITO_USER_POOL_ID"
echo "    Example: us-east-1_AbCdEfGhI"
echo ""
echo "[ ] DEV_COGNITO_CLIENT_ID"
echo "    Example: 1234567890abcdefghijklmnop"
echo ""
echo "Production Environment:"
echo "[ ] PROD_API_URL"
echo "    Example: https://xyz789.execute-api.us-east-1.amazonaws.com/v1"
echo ""
echo "[ ] PROD_COGNITO_USER_POOL_ID"
echo "    Example: us-east-1_XyZ123456"
echo ""
echo "[ ] PROD_COGNITO_CLIENT_ID"
echo "    Example: abcdefghijklmnop1234567890"
echo ""
echo "Temporary Values (if backend not ready):"
echo "You can use these placeholders to test the CI/CD:"
echo "  DEV_API_URL=https://api-dev.example.com"
echo "  DEV_COGNITO_USER_POOL_ID=temp-dev-pool"
echo "  DEV_COGNITO_CLIENT_ID=temp-dev-client"
echo ""
echo "After setting secrets, create a PR to test the deployment!"
