#!/bin/bash
# Quick script to update CI/CD workflow with actual backend values

echo "Update Frontend CI/CD with Backend Values"
echo "========================================"
echo ""
echo "Once your backend is deployed, update these values in .github/workflows/frontend-ci-cd.yml:"
echo ""
echo "For DEV environment (line ~115):"
echo "  VITE_API_URL=<Your API Gateway URL from backend>"
echo "  VITE_COGNITO_USER_POOL_ID=<Your Cognito User Pool ID>"
echo "  VITE_COGNITO_CLIENT_ID=<Your Cognito Client ID>"
echo ""
echo "For PROD environment (line ~220):"
echo "  VITE_API_URL=<Your Production API Gateway URL>"
echo "  VITE_COGNITO_USER_POOL_ID=<Your Production Cognito User Pool ID>"
echo "  VITE_COGNITO_CLIENT_ID=<Your Production Cognito Client ID>"
echo ""
echo "Example:"
echo "  VITE_API_URL=https://abc123.execute-api.us-east-1.amazonaws.com/v1"
echo "  VITE_COGNITO_USER_POOL_ID=us-east-1_AbCdEfGhI"
echo "  VITE_COGNITO_CLIENT_ID=1234567890abcdefghijklmnop"
echo ""
echo "You can get these values from:"
echo "1. AWS Console > API Gateway > Your API > Stages"
echo "2. AWS Console > Cognito > User Pools > Your Pool"
echo "3. Or from backend Terraform outputs"
